export const colors = {
  emergency:     '#FF3B30',
  safe:          '#34C759',
  info:          '#007AFF',
  warning:       '#FF9500',
  bgDark:        '#0D0D0D',
  cardDark:      '#1C1C1E',
  cardLight:     '#2C2C2E',
  textPrimary:   '#FFFFFF',
  textSecondary: '#8E8E93',
  border:        '#3A3A3C',
};

export const EMERGENCY_TYPES = [
  {
    id: 'Cardiac',
    emoji: '❤️',
    label: 'Cardiac',
    description: 'Heart attack, chest pain',
    priority: 'P1',
    color: '#FF3B30',
    needsICU: true,
  },
  {
    id: 'Stroke',
    emoji: '🧠',
    label: 'Stroke',
    description: 'Sudden numbness, confusion',
    priority: 'P1',
    color: '#FF6B35',
    needsICU: true,
  },
  {
    id: 'Accident',
    emoji: '🚗',
    label: 'Accident',
    description: 'Vehicle or fall injury',
    priority: 'P2',
    color: '#FF9500',
    needsICU: false,
  },
  {
    id: 'Breathing',
    emoji: '🫁',
    label: 'Breathing',
    description: 'Difficulty breathing',
    priority: 'P1',
    color: '#5E5CE6',
    needsICU: false,
  },
  {
    id: 'Injury',
    emoji: '🩹',
    label: 'Injury',
    description: 'Cut, fracture, burn',
    priority: 'P2',
    color: '#FF9500',
    needsICU: false,
  },
  {
    id: 'Unknown',
    emoji: '🆘',
    label: 'Unknown',
    description: 'Not sure, need help',
    priority: 'P2',
    color: '#8E8E93',
    needsICU: false,
  },
];
